import { GESTAO_TI_CATALOG_UPDATED_AT } from '../catalogVersion.js';
import type { CatalogConnection } from '../types.js';

const U = GESTAO_TI_CATALOG_UPDATED_AT;

/**
 * Conexões comprovadas no código (Fase 2).
 * IDs estáveis — não inventar ligações sem evidência.
 */
export const CATALOG_CONNECTIONS: CatalogConnection[] = [
  {
    id: 'conn-os-calc-utils',
    origin: 'missions (row)',
    destination: 'calculateMissionFinancials',
    type: 'calculates',
    rule: 'Motor de faturamento/custo por km/hora/tabelas',
    officialSource: 'lib/financialUtils.ts → calculateMissionFinancials',
    criticality: 'p0',
    monitoringStatus: 'partial',
    evidence: ['lib/financialUtils.ts', 'components/MissionFinancialModal.tsx'],
    writers: ['components/MissionFinancialModal.tsx', 'server/routes.ts (recalculate*)'],
    readers: ['lib/missionFinancialsCanonical.ts', 'components/ClientBillingReport.tsx'],
    updatedAt: U,
  },
  {
    id: 'conn-os-canonical-agg',
    origin: 'missions + tabelas preço',
    destination: 'computeCanonicalRevenueCost',
    type: 'aggregates',
    rule: 'Agregação canônica receita/custo/lucro para dashboards',
    officialSource: 'lib/missionFinancialsCanonical.ts',
    criticality: 'p0',
    monitoringStatus: 'partial',
    evidence: [
      'lib/missionFinancialsCanonical.ts',
      'lib/dashboardDiretoria/aggregations.ts',
      'components/ExecutiveDashboard.tsx',
    ],
    readers: [
      'lib/dashboardDiretoria/aggregations.ts',
      'components/ExecutiveDashboard.tsx',
      'components/MissionTable.tsx',
    ],
    updatedAt: U,
  },
  {
    id: 'conn-os-persist-front',
    origin: 'MissionFinancialModal',
    destination: 'missions.revenue_value / cost_value / toll_*',
    type: 'writes',
    rule: 'Gravação financeira via cliente Supabase (anon)',
    officialSource: 'missions (colunas salvas) quando aprovado',
    criticality: 'p0',
    monitoringStatus: 'unmonitored',
    evidence: ['components/MissionFinancialModal.tsx', 'lib/supabase.ts'],
    writers: ['components/MissionFinancialModal.tsx'],
    updatedAt: U,
  },
  {
    id: 'conn-os-recalc-api',
    origin: '/api/recalculate-open|/api/recalculate-all',
    destination: 'missions (valores recalculados)',
    type: 'writes',
    rule: 'Recálculo server-side com service_role',
    officialSource: 'calculateMissionFinancials via server/routes + api/recalculate-open',
    criticality: 'p1',
    monitoringStatus: 'partial',
    evidence: ['server/routes.ts', 'api/recalculate-open.ts'],
    writers: ['server/routes.ts', 'api/recalculate-open.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-os-scan-div',
    origin: '/api/missions/scan-divergences',
    destination: 'relatório saved vs recalculado',
    type: 'audits',
    rule: 'Detecta divergência entre valor salvo e motor',
    officialSource: 'scan-divergences (não altera dados)',
    criticality: 'p1',
    monitoringStatus: 'partial',
    evidence: ['server/routes.ts', 'scripts/diff-today.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-audit-system-logs',
    origin: 'lib/logger + UI/ops',
    destination: 'system_logs',
    type: 'audits',
    rule: 'Auditoria operacional/financeira em system_logs',
    officialSource: 'system_logs',
    criticality: 'p2',
    monitoringStatus: 'partial',
    evidence: ['lib/logger.ts', 'components/SystemLogs.tsx'],
    writers: ['lib/logger.ts', 'components/MissionFinancialModal.tsx'],
    readers: ['components/SystemLogs.tsx'],
    updatedAt: U,
  },
  {
    id: 'conn-medicao-missions',
    origin: 'missions (aprovadas)',
    destination: 'ClientBillingReport (boletim)',
    type: 'reads',
    rule: 'Boletim lê missões/período e monta medição',
    officialSource: 'missions + flags billing_approved',
    criticality: 'p1',
    monitoringStatus: 'unmonitored',
    evidence: ['components/ClientBillingReport.tsx'],
    readers: ['components/ClientBillingReport.tsx'],
    updatedAt: U,
  },
  {
    id: 'conn-toll-fields',
    origin: 'QualP/Gemini/manual',
    destination: 'missions.toll_value / toll_value_provider',
    type: 'writes',
    rule: 'Pedágio cliente vs fornecedor',
    officialSource: 'toll_value (cliente) / toll_value_provider (fornecedor) — ver lib/toll',
    criticality: 'p1',
    monitoringStatus: 'partial',
    evidence: ['lib/toll/clientTollBilling.ts', 'api/toll-qualp.ts', 'api/toll-gemini-estimate.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-asaas-webhook',
    origin: 'Asaas webhook',
    destination: 'financial_transactions / status cobrança',
    type: 'integrates',
    rule: 'Atualização de pagamento via webhook',
    officialSource: 'Asaas API + webhook /api/asaas/webhook',
    criticality: 'p0',
    monitoringStatus: 'monitored',
    evidence: ['server/routes.ts', 'server/asaasService.ts', 'api/asaas-status.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-asaas-charge',
    origin: 'UI/API create-charge',
    destination: 'Asaas cobrança',
    type: 'integrates',
    rule: 'Criação de cobrança',
    officialSource: 'Asaas',
    criticality: 'p1',
    monitoringStatus: 'monitored',
    evidence: ['api/asaas-create-charge.ts', 'server/asaasService.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-plugnotas-webhook',
    origin: 'PlugNotas webhook',
    destination: 'financial_invoices / NF',
    type: 'integrates',
    rule: 'Status de NF',
    officialSource: 'PlugNotas',
    criticality: 'p1',
    monitoringStatus: 'partial',
    evidence: ['server/plugnotasService.ts', 'server/routes.ts', 'server/nfRetryWorker.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-plugnotas-cron',
    origin: '/api/cron/nf-retry',
    destination: 'reprocessamento NF idempotente',
    type: 'triggers',
    rule: 'Retry de NF pendente',
    officialSource: 'nfRetryWorker',
    criticality: 'p2',
    monitoringStatus: 'partial',
    evidence: ['server/registerCronRoutes.ts', 'server/nfRetryWorker.ts', 'vercel.json'],
    updatedAt: U,
  },
  {
    id: 'conn-ap-ar-tx',
    origin: 'financial_transactions',
    destination: 'FinancialTransactionList',
    type: 'reads',
    rule: 'Contas a pagar/receber lidas do Supabase',
    officialSource: 'financial_transactions',
    criticality: 'p1',
    monitoringStatus: 'unmonitored',
    evidence: ['components/FinancialTransactionList.tsx'],
    updatedAt: U,
  },
  {
    id: 'conn-dre-agg',
    origin: 'financial_transactions + missions',
    destination: 'FinancialDRE',
    type: 'aggregates',
    rule: 'DRE gerencial agrega lançamentos/OS',
    officialSource: 'parcial — UI FinancialDRE',
    criticality: 'p2',
    monitoringStatus: 'unmonitored',
    evidence: ['components/FinancialDRE.tsx'],
    updatedAt: U,
  },
  {
    id: 'conn-balanco-snapshots',
    origin: 'account_balance_snapshots',
    destination: 'FinancialAccountManager / Cockpit',
    type: 'reads',
    rule: 'Snapshots de saldo de contas',
    officialSource: 'account_balance_snapshots',
    criticality: 'p2',
    monitoringStatus: 'unmonitored',
    evidence: ['components/FinancialAccountManager.tsx', 'server/routes.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-rh-employees',
    origin: 'rh_employees',
    destination: 'RH UI /api/rh/*',
    type: 'reads',
    rule: 'Cadastro de funcionários',
    officialSource: 'rh_employees',
    criticality: 'p2',
    monitoringStatus: 'partial',
    evidence: ['server/rhRoutes.ts', 'api/rh-employee-list.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-timeclock-punch',
    origin: '/api/rh/timeclock/punch',
    destination: 'time_clock',
    type: 'writes',
    rule: 'Batida de ponto (app + face)',
    officialSource: 'time_clock',
    criticality: 'p1',
    monitoringStatus: 'unmonitored',
    evidence: ['api/rh-timeclock-punch.ts', 'lib/timeclock/faceAuth.ts'],
    writers: ['api/rh-timeclock-punch.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-zapi-inbound',
    origin: 'Z-API webhook inbound',
    destination: 'whatsapp_messages / bot handlers',
    type: 'integrates',
    rule: 'Mensagens inbound',
    officialSource: 'Z-API + whatsapp_instances',
    criticality: 'p1',
    monitoringStatus: 'monitored',
    evidence: [
      'api/whatsapp/webhook/inbound.ts',
      'server/zapiWatchdog.ts',
      'api/zapi-health.ts',
    ],
    updatedAt: U,
  },
  {
    id: 'conn-zapi-cron',
    origin: '/api/cron/zapi',
    destination: 'watchdog / auto-reconnect',
    type: 'triggers',
    rule: 'Monitoramento contínuo da instância',
    officialSource: 'zapiWatchdog',
    criticality: 'p1',
    monitoringStatus: 'monitored',
    evidence: ['server/registerCronRoutes.ts', 'server/zapiWatchdog.ts', 'vercel.json'],
    updatedAt: U,
  },
  {
    id: 'conn-email-smtp',
    origin: 'emailService / fila',
    destination: 'Office365 SMTP',
    type: 'notifies',
    rule: 'Envio de e-mails operacionais',
    officialSource: 'SMTP Office365 (env EMAIL_*)',
    criticality: 'p2',
    monitoringStatus: 'monitored',
    evidence: ['server/emailService.ts', 'api/email-health.ts', 'server/clientEmailQueueWorker.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-email-cron',
    origin: '/api/cron/email-queue',
    destination: 'clientEmailQueueWorker',
    type: 'triggers',
    rule: 'Processa fila de e-mails',
    officialSource: 'fila interna',
    criticality: 'p2',
    monitoringStatus: 'monitored',
    evidence: ['api/cron/email-queue.ts', 'vercel.json'],
    updatedAt: U,
  },
  {
    id: 'conn-invest-api',
    origin: 'gestao-investimento-api',
    destination: 'tabelas investment_*',
    type: 'writes',
    rule: 'CRUD perfil/posições via service_role (handler leve)',
    officialSource: 'investor_profiles / investment_positions (manual XP)',
    criticality: 'p2',
    monitoringStatus: 'monitored',
    evidence: [
      'api/gestao-investimento-api.ts',
      'lib/investimentos/gestaoInvestimentoApi.ts',
      'lib/investimentos/dashboardCache.ts',
    ],
    cache: 'GESTAO_CACHE_TTL_MS ≈ 30 min',
    updatedAt: U,
  },
  {
    id: 'conn-gemini-health',
    origin: '/api/gemini/health',
    destination: 'Google Generative Language API',
    type: 'integrates',
    rule: 'Health da chave Gemini',
    officialSource: 'env GEMINI_* / AI_INTEGRATIONS_GEMINI_API_KEY',
    criticality: 'p2',
    monitoringStatus: 'monitored',
    evidence: ['api/gemini/health.ts', 'server/geminiClient.ts'],
    updatedAt: U,
  },
  {
    id: 'conn-cockpit-canonical',
    origin: 'missions',
    destination: 'Dashboard Diretoria KPIs',
    type: 'aggregates',
    rule: 'Cockpit usa agregações canônicas',
    officialSource: 'computeCanonicalRevenueCost',
    criticality: 'p1',
    monitoringStatus: 'partial',
    evidence: [
      'lib/dashboardDiretoria/aggregations.ts',
      'components/dashboard/DashboardDiretoria.tsx',
    ],
    updatedAt: U,
  },
];
