import type { CatalogModule } from '../types.js';

/** Módulos comprovados no repositório (Fase 2). */
export const CATALOG_MODULES: CatalogModule[] = [
  {
    id: 'mod-missions',
    name: 'Missões / OS',
    domain: 'operacao',
    screens: ['missions', 'mission-report', 'new-mission', 'shift-handover', 'ranking-dhl'],
    tables: ['missions', 'mission_logs', 'mission_history'],
    endpoints: [
      '/api/recalculate-open',
      '/api/recalculate-all',
      '/api/missions/scan-divergences',
      '/api/missions/fix-divergences',
    ],
    integrations: [],
    jobs: [],
    monitoringStatus: 'partial',
    evidence: ['components/MissionTable.tsx', 'lib/financialUtils.ts', 'server/routes.ts'],
  },
  {
    id: 'mod-audit-billing',
    name: 'Auditoria de faturamento',
    domain: 'financeiro',
    screens: ['fin-billing', 'system-logs'],
    tables: ['system_logs', 'missions'],
    endpoints: ['/api/missions/scan-divergences'],
    integrations: [],
    jobs: [],
    monitoringStatus: 'partial',
    evidence: ['lib/missionBillingAudit.ts', 'components/BillingAuditor.tsx', 'lib/logger.ts'],
  },
  {
    id: 'mod-medicao',
    name: 'Boletim de Medição',
    domain: 'financeiro',
    screens: ['fin-billing'],
    tables: ['missions', 'financial_transactions'],
    endpoints: [],
    integrations: [],
    jobs: [],
    monitoringStatus: 'unmonitored',
    evidence: ['components/ClientBillingReport.tsx', 'lib/billing/'],
  },
  {
    id: 'mod-faturamento',
    name: 'Faturamento OS',
    domain: 'financeiro',
    screens: ['fin-billing', 'fin-dashboard', 'diretoria-cockpit'],
    tables: ['missions'],
    endpoints: ['/api/recalculate-open', '/api/billing/recalculate-open'],
    integrations: [],
    jobs: [],
    monitoringStatus: 'partial',
    evidence: [
      'lib/missionFinancialsCanonical.ts',
      'lib/financialUtils.ts',
      'components/MissionFinancialModal.tsx',
    ],
  },
  {
    id: 'mod-asaas',
    name: 'Asaas',
    domain: 'integracao',
    screens: ['fin-transactions', 'fin-invoices'],
    tables: ['financial_transactions'],
    endpoints: ['/api/asaas/status', '/api/asaas/webhook', '/api/asaas/create-charge'],
    integrations: ['asaas'],
    jobs: [],
    monitoringStatus: 'monitored',
    evidence: ['server/asaasService.ts', 'api/asaas-status.ts', 'server/routes.ts'],
  },
  {
    id: 'mod-plugnotas',
    name: 'PlugNotas / NF',
    domain: 'integracao',
    screens: ['fin-invoices'],
    tables: ['financial_invoices'],
    endpoints: ['/api/plugnotas/status', '/api/plugnotas/webhook', '/api/nf/control'],
    integrations: ['plugnotas'],
    jobs: ['/api/cron/nf-retry'],
    monitoringStatus: 'partial',
    evidence: ['server/plugnotasService.ts', 'server/nfRetryWorker.ts', 'vercel.json'],
  },
  {
    id: 'mod-ap-ar',
    name: 'Contas a pagar / receber',
    domain: 'financeiro',
    screens: ['fin-transactions', 'fin-daily-movement'],
    tables: ['financial_transactions', 'financial_transaction_payments'],
    endpoints: [],
    integrations: ['asaas'],
    jobs: [],
    monitoringStatus: 'unmonitored',
    evidence: ['components/FinancialTransactionList.tsx', 'migrations/2026_07_20_financial_transaction_payments.sql'],
  },
  {
    id: 'mod-dre',
    name: 'DRE Gerencial',
    domain: 'financeiro',
    screens: ['fin-dre'],
    tables: ['financial_transactions', 'missions'],
    endpoints: [],
    integrations: [],
    jobs: [],
    monitoringStatus: 'unmonitored',
    evidence: ['components/FinancialDRE.tsx'],
  },
  {
    id: 'mod-balanco',
    name: 'Balanço / Contas bancárias',
    domain: 'financeiro',
    screens: ['fin-accounts', 'diretoria-cockpit'],
    tables: ['financial_accounts', 'account_balance_snapshots'],
    endpoints: [],
    integrations: [],
    jobs: [],
    monitoringStatus: 'unmonitored',
    evidence: ['components/FinancialAccountManager.tsx', 'migrations/'],
  },
  {
    id: 'mod-rh',
    name: 'RH',
    domain: 'rh',
    screens: ['rh-dashboard', 'rh-employees'],
    tables: ['rh_employees', 'rh_departments', 'rh_positions', 'rh_payroll_runs'],
    endpoints: ['/api/rh/health', '/api/rh/employees'],
    integrations: [],
    jobs: [],
    monitoringStatus: 'partial',
    evidence: ['server/rhRoutes.ts', 'migrations/2026_07_07_rh_module.sql'],
  },
  {
    id: 'mod-timeclock',
    name: 'Controle de ponto',
    domain: 'rh',
    screens: ['rh-timeclock'],
    tables: ['time_clock'],
    endpoints: ['/api/rh/timeclock/punch', '/api/rh/timeclock/entries'],
    integrations: [],
    jobs: [],
    monitoringStatus: 'unmonitored',
    evidence: ['api/rh-timeclock-punch.ts', 'lib/timeclock/', 'migrations/2026_07_08_timeclock_clt.sql'],
    notes: 'Control iD não está integrado no código atual; ponto usa biometria facial no app.',
  },
  {
    id: 'mod-whatsapp',
    name: 'WhatsApp / Z-API',
    domain: 'integracao',
    screens: ['system-settings'],
    tables: ['whatsapp_instances', 'whatsapp_messages'],
    endpoints: [
      '/api/zapi/health',
      '/api/whatsapp/webhook/inbound',
      '/api/whatsapp/telemetry/dashboard',
    ],
    integrations: ['z-api'],
    jobs: ['/api/cron/zapi'],
    monitoringStatus: 'monitored',
    evidence: [
      'api/zapi-health.ts',
      'server/zapiWatchdog.ts',
      'components/WhatsAppTelemetryDashboard.tsx',
    ],
  },
  {
    id: 'mod-email',
    name: 'E-mail SMTP',
    domain: 'integracao',
    screens: ['system-settings'],
    tables: [],
    endpoints: ['/api/email/health', '/api/email/mission-scheduled'],
    integrations: ['office365-smtp'],
    jobs: ['/api/cron/email-queue'],
    monitoringStatus: 'monitored',
    evidence: ['server/emailService.ts', 'api/email-health.ts', 'server/clientEmailQueueWorker.ts'],
  },
  {
    id: 'mod-investimentos',
    name: 'Gestão de Investimentos',
    domain: 'diretoria',
    screens: ['gestao-investimento'],
    tables: [
      'investor_profiles',
      'investment_positions',
      'investment_watchlists',
      'investment_data_sources',
      'investment_audit_log',
    ],
    endpoints: ['/api/gestao-investimento/health', '/api/gestao-investimento/summary'],
    integrations: [],
    jobs: ['/api/cron/gestao-investimento-schema', '/api/gestao-investimento/refresh-cache'],
    monitoringStatus: 'monitored',
    evidence: [
      'api/gestao-investimento-api.ts',
      'lib/investimentos/',
      'migrations/2026_08_04_gestao_investimento_fundacao.sql',
    ],
  },
  {
    id: 'mod-infra',
    name: 'Infra / Saúde da aplicação',
    domain: 'plataforma',
    screens: ['server-stats', 'system-diagnostics', 'gestor-desenvolvimento'],
    tables: ['system_logs'],
    endpoints: ['/api/health', '/api/version', '/api/system/diagnostics', '/api/supabase/health-check'],
    integrations: ['vercel', 'supabase'],
    jobs: ['/api/cron/minute', '/api/cron/maintenance'],
    monitoringStatus: 'monitored',
    evidence: ['api/health.ts', 'api/system-diagnostics.ts', 'components/ServerStats.tsx'],
  },
  {
    id: 'mod-gemini',
    name: 'Gemini / IA',
    domain: 'integracao',
    screens: ['cost-optimization', 'diretoria-cockpit'],
    tables: ['billing_usage'],
    endpoints: ['/api/gemini/health', '/api/gemini/generate'],
    integrations: ['gemini'],
    jobs: ['/api/cron/billing-sync'],
    monitoringStatus: 'monitored',
    evidence: ['api/gemini/health.ts', 'server/geminiClient.ts', 'lib/billing/billingService.ts'],
  },
];
