import type { SsotEntry } from '../types.js';

/** Fontes de verdade documentadas com evidência — Fase 2 não corrige duplicidades. */
export const CATALOG_SSOT: SsotEntry[] = [
  {
    id: 'ssot-os-revenue-cost',
    dataLabel: 'Receita / custo / lucro da OS',
    officialSource:
      'Documentado: lib/missionFinancialsCanonical.ts (computeCanonicalRevenueCost). Persistência: missions.revenue_value / cost_value quando aprovado.',
    writers: [
      'components/MissionFinancialModal.tsx (Supabase anon)',
      'server/routes.ts recalculate-*',
      'api/recalculate-open.ts',
    ],
    readers: [
      'lib/dashboardDiretoria/aggregations.ts',
      'components/ExecutiveDashboard.tsx',
      'components/ClientBillingReport.tsx',
      'components/MissionTable.tsx',
    ],
    recalculators: [
      'lib/financialUtils.ts → calculateMissionFinancials',
      '/api/recalculate-open',
      '/api/recalculate-all',
      '/api/missions/fix-divergences',
    ],
    fallbacks: ['Estimativa via tabelas quando valor não salvo (canônico source=estimated|mixed)'],
    divergenceRisk: 'alto',
    state: 'duplicado',
    evidence: [
      'lib/missionFinancialsCanonical.ts (comentário SSOT + histórico 640k/630k/627k)',
      'components/MissionFinancialModal.tsx',
      'server/routes.ts (scan-divergences / fix-divergences)',
    ],
  },
  {
    id: 'ssot-toll',
    dataLabel: 'Pedágio cliente / fornecedor',
    officialSource: 'missions.toll_value (cliente) e missions.toll_value_provider (fornecedor)',
    writers: ['MissionFinancialModal', 'libs toll / QualP / Gemini estimate'],
    readers: ['missionFinancialsCanonical', 'missionBillingAudit', 'boletim'],
    recalculators: ['lib/toll/*', 'api/toll-qualp', 'api/toll-gemini-estimate'],
    fallbacks: ['toll_value_provider pode cair para toll_value na leitura'],
    divergenceRisk: 'medio',
    state: 'parcial',
    evidence: ['lib/toll/clientTollBilling.ts', 'lib/missionFinancialsCanonical.ts'],
  },
  {
    id: 'ssot-billing-approved',
    dataLabel: 'Status de aprovação de faturamento da OS',
    officialSource: 'missions.billing_approved / billing_verified_by',
    writers: ['components/MissionFinancialModal.tsx'],
    readers: ['computeCanonicalRevenueCost', 'ClientBillingReport'],
    recalculators: [],
    fallbacks: [],
    divergenceRisk: 'medio',
    state: 'confirmado',
    evidence: ['lib/missionFinancialsCanonical.ts', 'components/MissionFinancialModal.tsx'],
  },
  {
    id: 'ssot-mission-status',
    dataLabel: 'Status da missão',
    officialSource: 'missions.status',
    writers: ['MissionForm', 'UpdateMissionModal', 'fluxos operacionais'],
    readers: ['MissionTable', 'dashboards', 'canônico (REFUSED→zero)'],
    recalculators: [],
    fallbacks: [],
    divergenceRisk: 'baixo',
    state: 'confirmado',
    evidence: ['types.ts', 'lib/missionFinancialsCanonical.ts'],
  },
  {
    id: 'ssot-asaas-payment',
    dataLabel: 'Status de cobrança Asaas',
    officialSource: 'Asaas (webhook + APIs) refletido em financial_transactions',
    writers: ['/api/asaas/webhook', 'asaasService'],
    readers: ['telas financeiras'],
    recalculators: ['api/asaas-sync-payment-status'],
    fallbacks: [],
    divergenceRisk: 'medio',
    state: 'parcial',
    evidence: ['server/asaasService.ts', 'api/asaas-status.ts'],
  },
  {
    id: 'ssot-nf',
    dataLabel: 'Status de NF (PlugNotas)',
    officialSource: 'PlugNotas + financial_invoices',
    writers: ['webhook PlugNotas', 'nfRetryWorker'],
    readers: ['fin-invoices'],
    recalculators: ['/api/cron/nf-retry'],
    fallbacks: [],
    divergenceRisk: 'medio',
    state: 'parcial',
    evidence: ['server/plugnotasService.ts', 'server/nfRetryWorker.ts'],
  },
  {
    id: 'ssot-timeclock',
    dataLabel: 'Batidas / total trabalhado',
    officialSource: 'time_clock (API RH)',
    writers: ['api/rh-timeclock-punch', 'api/rh-timeclock-adjust'],
    readers: ['rh-timeclock UI'],
    recalculators: [],
    fallbacks: ['FaceAuth no client'],
    divergenceRisk: 'medio',
    state: 'parcial',
    evidence: ['api/rh-timeclock-punch.ts', 'migrations/2026_07_08_timeclock_clt.sql'],
  },
  {
    id: 'ssot-whatsapp-instance',
    dataLabel: 'Credencial/status instância WhatsApp',
    officialSource: 'whatsapp_instances (+ sync env ZAPI_MOBILE_*)',
    writers: ['syncMobileInstanceFromEnv', 'painéis reconnect', 'webhooks connection'],
    readers: ['zapiWatchdog', 'WhatsAppOfflineModal', '/api/zapi/health'],
    recalculators: [],
    fallbacks: ['ZAPI_INSTANCE_ID / ZAPI_TOKEN legado'],
    divergenceRisk: 'medio',
    state: 'parcial',
    evidence: ['AGENTS.md', 'api/zapi-health.ts', 'server/zapiWatchdog.ts'],
  },
  {
    id: 'ssot-audit-hub',
    dataLabel: 'Trilha de auditoria geral',
    officialSource: 'system_logs (hub principal); existem rh_audit_logs, investment_audit_log, audit_logs',
    writers: ['lib/logger.ts', 'vários componentes/APIs'],
    readers: ['components/SystemLogs.tsx'],
    recalculators: [],
    fallbacks: [],
    divergenceRisk: 'alto',
    state: 'duplicado',
    evidence: ['lib/logger.ts', 'lib/rh/audit.ts', 'lib/investimentos/gestaoInvestimentoApi.ts'],
  },
  {
    id: 'ssot-invest-positions',
    dataLabel: 'Posições de investimento (manual XP)',
    officialSource: 'investment_positions',
    writers: ['api/gestao-investimento-api (service_role)'],
    readers: ['GestaoInvestimento UI', 'summary'],
    recalculators: [],
    fallbacks: ['cache dashboard 30 min'],
    divergenceRisk: 'baixo',
    state: 'confirmado',
    evidence: ['lib/investimentos/gestaoInvestimentoApi.ts', 'lib/investimentos/dashboardCache.ts'],
  },
];
