// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dhl-open-status/StatusCard.tsx": () => import("../components/mockups/dhl-open-status/StatusCard.tsx"),
  "./components/mockups/dhl-finalize/FinalizeChecklist.tsx": () => import("../components/mockups/dhl-finalize/FinalizeChecklist.tsx")
};
